$(document).ready(function(){
   $('.collapsible').collapsible();
 });
 $(document).ready(function(){
   $('.carousel').carousel();
 });
 $(document).ready(function(){
$('.sidenav').sidenav();
});
